spring.application.name=sdp36BE
spring.datasource.url=jdbc:mysql://localhost:3306/healthwell_db
spring.datasource.username=root
spring.datasource.password=Ak@sql10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9090

# Email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arundluffy1410@gmail.com
spring.mail.password=bfqu uczu kpvr bcux
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

